include: package:very_good_analysis/analysis_options.9.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    use_setters_to_change_properties: false
    avoid_positional_boolean_parameters: false
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    invalid_annotation_target: ignore
    no_default_cases: ignore
    unused_result: ignore
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
